services:
  mongo:
    image: mongo:8.0
    restart: unless-stopped
    # izquierda: puerto de mi máquina, derecha: puerto del contenedor
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - backend_uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:8080"

volumes:
  mongo_data:
  backend_uploads:
